### ISSUE TITLE
Thunder error exit

### ISSUE THREAD

**Issue by speeed001** [pouriap/Grabby#3]
Download chosen Thunder
Closing Firefox will also cause Thunder to exit

Please fix it. thank
thunder link :https://xl11.xunlei.com/

**Comment by pouriap** [comment]
Hi.

Thunder is not officially supported.
In fact I couldn't even find it online. Until now thanks to you.

It looks like it only supports Chinese language. I couldn't even open the site, I had to use a Hong Kong VPN to download it.
So it might not be that easy to integrate it. But I will try.

Recently I've been revisiting this addon and trying to finally add the media grabbing feature into it which lets you download videos too. I don't promise a new release anytime soon but I will definitely add Thunder to my to-do list.

Thanks for bringing this into my attention.

**Comment by benzBrake** [comment]
I'm using this extension with thunder version 11 on Windows 11, but I can't repoduce this error, can you provide more information to reproduce this error, usch as windows version, the steps to reproduce this error?

**Comment by speeed001** [comment]
> I'm using this extension with thunder version 11 on Windows 11, but I can't repoduce this error, can you provide more information to reproduce this error, usch as windows version, the steps to reproduce this error?
win11 22000.795.
I can reproduce this problem on my laptop and PC
![gif](https://user-images.githubusercontent.com/22834701/179224970-35589617-1baa-40b2-b383-9a424ec0f864.gif)

**Comment by pouriap** [comment]
This should only happen when Thunder is closed and is opened when you start a download in Firefox.
You should open Thunder first, or set it to start with windows, and then when you exit Firefox it shouldn't get closed.

**Comment by pouriap** [comment]
I changed the method that launches the download managers in v0.62 and it doesn't happen anymore.

There is a possibility that the new method might create other bugs. If it doesn't then this issue will be solved.
If it does then I'll have to go back to the previous method and you'll have to start download managers before opening Firefox.
