### ISSUE TITLE
Where can I download Host for Download Grab?

### ISSUE THREAD

**Issue by bremaya** [pouriap/Grabby#7]
I searched Github and the web and I didn't find the link to download the Native Host for the addon...

**Comment by pouriap** [comment]
Hi
You can download it here
https://github.com/pouriap/Grabby/releases/download/v0.11.1a/Download.Grab.Native.Host.v0.11.1a.Setup.exe

**Comment by pouriap** [comment]
The new release is ready https://github.com/pouriap/Grabby/releases/tag/v0.60.0a
