### ISSUE TITLE
Thunder still appear in the Default Download Manager despite I already uninstall it

### ISSUE THREAD

**Issue by BladeRider** [pouriap/Grabby#8]
Hello Developer

Thank you for developing this awesome addon. I have two different download manager installed in my PC. One is Internet Download Manager, another one is the Chinese Thunder. I use Internet Download Manager as the main download manager. 

After i install the latest update (both addon and toolkit), Grabby set Thunder as the default download manager and of course Overriding Firefox's download dialog will not appear. Then i try to change and save Internet Download Manager as the default but the Overriding Firefox's download dialog still not functioning and Grabby still set Thunder as default after reopen Firefox.

 I have uninstall Thunder completely. reinstall both Grabby & firefox but Grabby still sees the Thunder (which is a bit weird as Thunder is no longer inside my computer) and Overriding Firefox's download dialog will not appear at all. 
 
 Is there anything i can do to fix this issue? Thank you

**Comment by pouriap** [comment]
Hello.

Regarding the default download manager it looks like there is a bug and it is not saved. I will fix it soon.

But the override dialog not appearing is strange, it has never happened in my experience. 
What version of Firefox are you using?

Please do the following steps so I can see what is wrong:
1- Go to Firefox's adddon debugging page by opening this link: [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)
2- There is a list of all of your addons. Find Grabby and click "**inspect**"
3- Now the debugger for Grabby will open. Click on the "**console**" tab
4- Now open a new tab and go to a download page and click on a download link
5- Go back to the debugging tab and right click on the console output where the messages are being shown and click "**copy all messages**"

Then paste those messages here.

Finally thank you for using Grabby and thanks for your feedback.
I don't remember if it was you or somebody else but I already promised to add Thunder(Xunlei) to Grabby and I'm going to do it soon.

**Comment by BladeRider** [comment]
Hello,
thanks for replying. 

Currently i am using Firefox 111.0.1 64 bit. I have managed to solve the override dialog not appearing issue on my side. Because I am away from that particular computer most of the time, so i am using Microsoft Remote Desktop Connection to remote control that particular PC and i found out that during the 1st time i st up Grabby, I have to be physically in front of the computer to setup it else override dialog will not appear. Once the override dialog appeared, i can continue using it via remote desktop.

**Comment by pouriap** [comment]
Glad to hear that. So you have to run the installer when physically using that PC and then it works?

Regarding the default download manager not being saved issue I just released an update that fixes it.

Regarding thunder still being shown after uninstall, it's probably because Thunder doesn't fully delete everything from registry. If you really want to remove it you can try the following:

- Press Windows key + R
- type `regedit` and press enter
- Go to `HKEY_LOCAL_MACHINE\SOFTWARE\Classes`
- Scroll all the way down and delete the key `ThunderAgent.Agent`. 

This should remove thunder from the download managers list.

**Comment by BladeRider** [comment]
Thank you. 
The registry method works!
Thank you for making such a great addon.
Cheers
