### ISSUE TITLE
Error could not connect to native app

### ISSUE THREAD

**Issue by LordSpectre** [pouriap/Grabby#9]
Hi, thank you very much to developing a flashgot-like app, I'm testing it in a VM with the Firefox 112.0b9 (32 bit). I also tried the Firefox developer edition with the same issue anyway.

Installed a fresh copy of Firefox 111.0.1 (64 bit)
Installed Grabby-Toolkit-0.61.3-Setup.exe
Installed addon from there: https://addons.mozilla.org/en-US/firefox/addon/grabby/

But as soon I open firefox I get:
![Image_002](https://user-images.githubusercontent.com/34072256/230565877-53edc906-7816-40d3-b20d-987c37cf53c0.png)
And the addon option page is empty.

I tried to reboot pc, reinstall Grabby-Toolkit, reinstall addon, but nothing, I still get such error.
Any clue? Any action I missed?
Thank you

**EDIT:** I tried in a real PC (not a VM) and I didn't get the above error, however, still don't get grabby window, instead firefox show me a classic download window. In grabby setting, I still get a white page.

**Comment by pouriap** [comment]
It probably has something to do with creating registry keys by the setup program. Another user was also having a problem with installing it with remote desktop.

If you could please follow the instructions below it may resolve your issue and help resolve other people's issues as well.

[Download this zip file](https://www.dropbox.com/s/890wisb2yo2rrgs/setup-files.zip?dl=1) which contains two different setup files.
One is called `setup-non-admin.exe` and the other is `setup-admin.exe`.

Close all instances of Firefox first and then uninstall the current toolkit.

After that first try the **non-admin** setup then open Firefox again and see if the issue is resolved.
If it didn't, close Firefox again and uninstall the toolkit and this time try the `setup-admin.exe`.

**Comment by LordSpectre** [comment]
Hi, unfortunately both setup didn't worked for me. This is what I did:

Windows 10 VM
- Install/uninstall different toolkit version
- Tested both toolkit version in a clean Windows 10 installation. I used VM snapshot to be sure no previous regkey leftover 
Still get "Could not connect to native App"

Windows 11 "real" PC
Tested both setup, installing/uninstalling, no "Could not connect to native App" but no override window and the addon setup page is totally empty.

Hope you can solve this issue, since I really need this addon :)

**Comment by LordSpectre** [comment]
> Where do you install the toolkit?

What you mean with "where"?
I left the deafult directory: C:\Program Files (x86)\Grabby Toolkit

**Comment by pouriap** [comment]
Try installing it in a user-specific directory like `C:\Users\YOUR_NAME` or on your desktop or in another drive.

**Comment by LordSpectre** [comment]
No way, used:
C:\Users\Administrator\Grabby Toolkit
D:\Grabby Toolkit

**Comment by pouriap** [comment]
Please open the debug output page using [this guide](https://github.com/pouriap/Grabby/wiki/How-to-open-the-debug-console-and-copy-messages) and then post the console output in here.

Make sure to open the options page once so I can see any errors that it outputs too.

**Comment by LordSpectre** [comment]
> Uncaught (in promise) Error: Native App not found
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:9
    <anonymous> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/background.js:34
log.js:9:19
Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/messaging.js:130
log.js:12:21
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:12
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
Uncaught (in promise) Error: error in rendering view
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:13
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    async* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    EventListener.handleEvent* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
log.js:13:19
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:23
    AsyncFunctionThrow self-hosted:814
    (Asinc.: async)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/messaging.js:130
log.js:12:21
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:12
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
Uncaught (in promise) Error: error in rendering view
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:13
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    async* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    EventListener.handleEvent* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
log.js:13:19
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:23
    AsyncFunctionThrow self-hosted:814
    (Asinc.: async)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/messaging.js:130
log.js:12:21
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:12
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
Uncaught (in promise) Error: error in rendering view
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:13
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    async* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    EventListener.handleEvent* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
log.js:13:19
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:23
    AsyncFunctionThrow self-hosted:814
    (Asinc.: async)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:16
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/popup/popup.js:14
Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/messaging.js:130
log.js:12:21
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:12
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/options_page/options.js:140
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/options_page/options.js:139
Uncaught (in promise) Error: error in rendering view
    err moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/scripts/log.js:13
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:21
    async* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/options_page/options.js:140
    EventListener.handleEvent* moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/options_page/options.js:139
log.js:13:19
    render moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/view.js:23
    AsyncFunctionThrow self-hosted:814
    (Asinc.: async)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/options_page/options.js:140
    (Asinc.: EventListener.handleEvent)
    <anonima> moz-extension://33f73e42-98cb-4331-8d06-e726ace43c4a/views/options_page/options.js:139

**Comment by LordSpectre** [comment]
If you want I can give you complete access to the VM

**Comment by pouriap** [comment]
I still suspect there's a problem with the installer.

How do I access the VM?

**Comment by LordSpectre** [comment]
TeamViever? Any pther desktop share is ok for me.
Is there a way to contact you in private? Just to share the credentials. My Skype: kr0n0shqf

**Comment by pouriap** [comment]
Send me a DM on discord

**Comment by LordSpectre** [comment]
> Send me a DM on discord

How can I find you in discord?

**Comment by pouriap** [comment]
There were two problems: The installer did not set the 64bit registry values in some systems and also I forgot to include the VC++ Redistributables with the setup. The latest version of the toolkit should fix all the issues.
